name: Check imports
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - uses: actions/checkout@master
    - name: Check imports
      shell: bash
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        go get golang.org/x/tools/cmd/goimports
        diff -u <(echo -n) <(goimports -d .)
